### ISSUE TITLE
Could you share the “requirements.txt“?

### ISSUE THREAD

**Issue by TainanKyle** [ArmastusChen/Learning-Continuous-Implicit-Representation-for-Near-Periodic-Patterns#3]
Hi, 
Thank you for your great work. I tried to run your project but found out that the “requirements.txt“ seems to be missing. Could you share the file?

**Comment by ArmastusChen** [comment]
Hi, 

Thanks for your pointing this out. I have uploaded the file, could you please try it and see if it works?

**Comment by TainanKyle** [comment]
Hi, 

Thank you for the quick reply and sharing the file. I have tried to set up the environment with the file, but there were still some errors.
The followings are the error message:

```
WARNING: Generating metadata for package OleFileIO_PL produced metadata for project name olefile. Fix your #egg=OleFileIO_PL fragments.
Discarding https://files.pythonhosted.org/packages/a0/05/f124ecb536ae2090891d3bcb6a65facd1358f4fd10422c1354357687e8dc/OleFileIO_PL-0.42.1.zip (from https://pypi.org/simple/olefileio-pl/): Requested olefile from https://files.pythonhosted.org/packages/a0/05/f124ecb536ae2090891d3bcb6a65facd1358f4fd10422c1354357687e8dc/OleFileIO_PL-0.42.1.zip (from -r requirements.txt (line 9)) has inconsistent name: expected 'olefileio-pl', but metadata has 'olefile'
  Using cached OleFileIO_PL-0.41.zip (118 kB)
  Preparing metadata (setup.py) ... done
  WARNING: Generating metadata for package OleFileIO_PL produced metadata for project name olefile. Fix your #egg=OleFileIO_PL fragments.
Discarding https://files.pythonhosted.org/packages/1a/5b/3c6803bb51336b71525bce4c811c598107073dc642c9fafffc6a79b0e4b7/OleFileIO_PL-0.41.zip (from https://pypi.org/simple/olefileio-pl/): Requested olefile from https://files.pythonhosted.org/packages/1a/5b/3c6803bb51336b71525bce4c811c598107073dc642c9fafffc6a79b0e4b7/OleFileIO_PL-0.41.zip (from -r requirements.txt (line 9)) has inconsistent name: expected 'olefileio-pl', but metadata has 'olefile'
  Using cached OleFileIO_PL-0.40.zip (111 kB)
  Preparing metadata (setup.py) ... done
  WARNING: Generating metadata for package OleFileIO_PL produced metadata for project name olefile. Fix your #egg=OleFileIO_PL fragments.
Discarding https://files.pythonhosted.org/packages/1b/8b/26fe3d9215c4c88f9b8c925b235b352269e59ba81a97951f4a80470967ef/OleFileIO_PL-0.40.zip (from https://pypi.org/simple/olefileio-pl/): Requested olefile from https://files.pythonhosted.org/packages/1b/8b/26fe3d9215c4c88f9b8c925b235b352269e59ba81a97951f4a80470967ef/OleFileIO_PL-0.40.zip (from -r requirements.txt (line 9)) has inconsistent name: expected 'olefileio-pl', but metadata has 'olefile'
  Using cached OleFileIO_PL-0.31.zip (80 kB)
  Preparing metadata (setup.py) ... done
Collecting opencv_python==4.5.1.48 (from -r requirements.txt (line 10))
  Using cached opencv_python-4.5.1.48-cp38-cp38-manylinux2014_x86_64.whl.metadata (17 kB)
Collecting pandas==1.1.3 (from -r requirements.txt (line 11))
  Using cached pandas-1.1.3-cp38-cp38-manylinux1_x86_64.whl.metadata (4.7 kB)
Collecting Pillow==8.4.0 (from -r requirements.txt (line 12))
  Using cached Pillow-8.4.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.5 kB)
Collecting planar==0.4 (from -r requirements.txt (line 13))
  Using cached planar-0.4.zip (622 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      Traceback (most recent call last):
        File "/tmp/pip-install-yal_a391/planar_671f4fceb094413da6bda7ff35c092aa/setup.py", line 11, in <module>
          from distutils.command.build_py import build_py_2to3 as build_py
      ImportError: cannot import name 'build_py_2to3' from 'distutils.command.build_py' (/home/kylehuang/anaconda3/envs/NPPnet/lib/python3.8/site-packages/setuptools/_distutils/command/build_py.py)
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-yal_a391/planar_671f4fceb094413da6bda7ff35c092aa/setup.py", line 14, in <module>
          raise ImportError("build_py_2to3 not found in distutils - it is required for Python 3.x")
      ImportError: build_py_2to3 not found in distutils - it is required for Python 3.x
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

I'm wondering if you know how to fix this error.

**Comment by ArmastusChen** [comment]
> Hi,
> 
> Thank you for the quick reply and sharing the file. I have tried to set up the environment with the file, but there were still some errors. The followings are the error message:
> 
> ```
> WARNING: Generating metadata for package OleFileIO_PL produced metadata for project name olefile. Fix your #egg=OleFileIO_PL fragments.
> Discarding https://files.pythonhosted.org/packages/a0/05/f124ecb536ae2090891d3bcb6a65facd1358f4fd10422c1354357687e8dc/OleFileIO_PL-0.42.1.zip (from https://pypi.org/simple/olefileio-pl/): Requested olefile from https://files.pythonhosted.org/packages/a0/05/f124ecb536ae2090891d3bcb6a65facd1358f4fd10422c1354357687e8dc/OleFileIO_PL-0.42.1.zip (from -r requirements.txt (line 9)) has inconsistent name: expected 'olefileio-pl', but metadata has 'olefile'
>   Using cached OleFileIO_PL-0.41.zip (118 kB)
>   Preparing metadata (setup.py) ... done
>   WARNING: Generating metadata for package OleFileIO_PL produced metadata for project name olefile. Fix your #egg=OleFileIO_PL fragments.
> Discarding https://files.pythonhosted.org/packages/1a/5b/3c6803bb51336b71525bce4c811c598107073dc642c9fafffc6a79b0e4b7/OleFileIO_PL-0.41.zip (from https://pypi.org/simple/olefileio-pl/): Requested olefile from https://files.pythonhosted.org/packages/1a/5b/3c6803bb51336b71525bce4c811c598107073dc642c9fafffc6a79b0e4b7/OleFileIO_PL-0.41.zip (from -r requirements.txt (line 9)) has inconsistent name: expected 'olefileio-pl', but metadata has 'olefile'
>   Using cached OleFileIO_PL-0.40.zip (111 kB)
>   Preparing metadata (setup.py) ... done
>   WARNING: Generating metadata for package OleFileIO_PL produced metadata for project name olefile. Fix your #egg=OleFileIO_PL fragments.
> Discarding https://files.pythonhosted.org/packages/1b/8b/26fe3d9215c4c88f9b8c925b235b352269e59ba81a97951f4a80470967ef/OleFileIO_PL-0.40.zip (from https://pypi.org/simple/olefileio-pl/): Requested olefile from https://files.pythonhosted.org/packages/1b/8b/26fe3d9215c4c88f9b8c925b235b352269e59ba81a97951f4a80470967ef/OleFileIO_PL-0.40.zip (from -r requirements.txt (line 9)) has inconsistent name: expected 'olefileio-pl', but metadata has 'olefile'
>   Using cached OleFileIO_PL-0.31.zip (80 kB)
>   Preparing metadata (setup.py) ... done
> Collecting opencv_python==4.5.1.48 (from -r requirements.txt (line 10))
>   Using cached opencv_python-4.5.1.48-cp38-cp38-manylinux2014_x86_64.whl.metadata (17 kB)
> Collecting pandas==1.1.3 (from -r requirements.txt (line 11))
>   Using cached pandas-1.1.3-cp38-cp38-manylinux1_x86_64.whl.metadata (4.7 kB)
> Collecting Pillow==8.4.0 (from -r requirements.txt (line 12))
>   Using cached Pillow-8.4.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.5 kB)
> Collecting planar==0.4 (from -r requirements.txt (line 13))
>   Using cached planar-0.4.zip (622 kB)
>   Preparing metadata (setup.py) ... error
>   error: subprocess-exited-with-error
>   
>   × python setup.py egg_info did not run successfully.
>   │ exit code: 1
>   ╰─> [13 lines of output]
>       Traceback (most recent call last):
>         File "/tmp/pip-install-yal_a391/planar_671f4fceb094413da6bda7ff35c092aa/setup.py", line 11, in <module>
>           from distutils.command.build_py import build_py_2to3 as build_py
>       ImportError: cannot import name 'build_py_2to3' from 'distutils.command.build_py' (/home/kylehuang/anaconda3/envs/NPPnet/lib/python3.8/site-packages/setuptools/_distutils/command/build_py.py)
>       
>       During handling of the above exception, another exception occurred:
>       
>       Traceback (most recent call last):
>         File "<string>", line 2, in <module>
>         File "<pip-setuptools-caller>", line 34, in <module>
>         File "/tmp/pip-install-yal_a391/planar_671f4fceb094413da6bda7ff35c092aa/setup.py", line 14, in <module>
>           raise ImportError("build_py_2to3 not found in distutils - it is required for Python 3.x")
>       ImportError: build_py_2to3 not found in distutils - it is required for Python 3.x
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: metadata-generation-failed
> 
> × Encountered error while generating package metadata.
> ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip.
> hint: See above for details.
> ```
> 
> I'm wondering if you know how to fix this error.

Hi,

Sorry for the late reply. I uploaded a newer version. I tested it on a single NVIDIA TITAN GPU and it works.  But you may need a newer pytorch verison if you have a newer GPU. 

Please let me know if it works.

**Comment by TainanKyle** [comment]
Hi,

Thank you for the update. It works on my computer. I’ll close this issue. Thank you again for your help.
